apiVersion: v1
kind: Namespace
metadata:
  name: quant-dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quant-results-pvc
  namespace: quant-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
